# Reference:
#   https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: pip
    directory: /     # pyproject.toml, poetry.lock
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /ci   # requirements.txt et al.
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /ci/demonet
    schedule:
      interval: weekly
