"""
This type stub file was generated by pyright.
"""

def recursive_levenshtein(
    string_1, string_2, len_1=..., len_2=..., offset_1=..., offset_2=..., memo=...
):
    """
    Calculates the Levenshtein distance between two strings.

    Usage::

        >>> recursive_levenshtein('kitten', 'sitting')
        3
        >>> recursive_levenshtein('kitten', 'kitten')
        0
        >>> recursive_levenshtein('', '')
        0

    """
    ...
