"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
P4Testgen Protobuf template."""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from ..p4.v1 import p4runtime_pb2 as _p4runtime_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class InputPacketAtPort(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PACKET_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    packet: _builtins.bytes
    """The raw bytes of the test packet."""
    port: _builtins.int
    """The raw bytes of the port associated with the packet."""
    def __init__(
        self,
        *,
        packet: _builtins.bytes = ...,
        port: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["packet", b"packet", "port", b"port"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InputPacketAtPort: _TypeAlias = InputPacketAtPort  # noqa: Y015

@_typing.final
class OutputPacketAtPort(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PACKET_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    PACKET_MASK_FIELD_NUMBER: _builtins.int
    packet: _builtins.bytes
    """The raw bytes of the test packet."""
    port: _builtins.int
    """The raw bytes of the port associated with the packet."""
    packet_mask: _builtins.bytes
    """The don't care mask of the packet."""
    def __init__(
        self,
        *,
        packet: _builtins.bytes = ...,
        port: _builtins.int = ...,
        packet_mask: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["packet", b"packet", "packet_mask", b"packet_mask", "port", b"port"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OutputPacketAtPort: _TypeAlias = OutputPacketAtPort  # noqa: Y015

@_typing.final
class TestCase(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INPUT_PACKET_FIELD_NUMBER: _builtins.int
    EXPECTED_OUTPUT_PACKET_FIELD_NUMBER: _builtins.int
    ENTITIES_FIELD_NUMBER: _builtins.int
    TRACES_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def input_packet(self) -> Global___InputPacketAtPort:
        """The input packet."""

    @_builtins.property
    def expected_output_packet(self) -> _containers.RepeatedCompositeFieldContainer[Global___OutputPacketAtPort]:
        """The corresponding expected output packet."""

    @_builtins.property
    def entities(self) -> _containers.RepeatedCompositeFieldContainer[_p4runtime_pb2.Entity]:
        """The entities (e.g., table entries) to install on the switch before
        injecting the `input_packet`.
        """

    @_builtins.property
    def traces(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The trace associated with this particular test."""

    @_builtins.property
    def metadata(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Additional metadata and information."""

    def __init__(
        self,
        *,
        input_packet: Global___InputPacketAtPort | None = ...,
        expected_output_packet: _abc.Iterable[Global___OutputPacketAtPort] | None = ...,
        entities: _abc.Iterable[_p4runtime_pb2.Entity] | None = ...,
        traces: _abc.Iterable[_builtins.str] | None = ...,
        metadata: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["input_packet", b"input_packet"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entities", b"entities", "expected_output_packet", b"expected_output_packet", "input_packet", b"input_packet", "metadata", b"metadata", "traces", b"traces"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TestCase: _TypeAlias = TestCase  # noqa: Y015
