"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
This package and its contents are a work-in-progress."""

from collections import abc as _abc
from google.protobuf import any_pb2 as _any_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from . import p4types_pb2 as _p4types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class P4Info(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PKG_INFO_FIELD_NUMBER: _builtins.int
    TABLES_FIELD_NUMBER: _builtins.int
    ACTIONS_FIELD_NUMBER: _builtins.int
    ACTION_PROFILES_FIELD_NUMBER: _builtins.int
    COUNTERS_FIELD_NUMBER: _builtins.int
    DIRECT_COUNTERS_FIELD_NUMBER: _builtins.int
    METERS_FIELD_NUMBER: _builtins.int
    DIRECT_METERS_FIELD_NUMBER: _builtins.int
    CONTROLLER_PACKET_METADATA_FIELD_NUMBER: _builtins.int
    VALUE_SETS_FIELD_NUMBER: _builtins.int
    REGISTERS_FIELD_NUMBER: _builtins.int
    DIGESTS_FIELD_NUMBER: _builtins.int
    EXTERNS_FIELD_NUMBER: _builtins.int
    TYPE_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pkg_info(self) -> Global___PkgInfo: ...
    @_builtins.property
    def tables(self) -> _containers.RepeatedCompositeFieldContainer[Global___Table]: ...
    @_builtins.property
    def actions(self) -> _containers.RepeatedCompositeFieldContainer[Global___Action]: ...
    @_builtins.property
    def action_profiles(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActionProfile]: ...
    @_builtins.property
    def counters(self) -> _containers.RepeatedCompositeFieldContainer[Global___Counter]: ...
    @_builtins.property
    def direct_counters(self) -> _containers.RepeatedCompositeFieldContainer[Global___DirectCounter]: ...
    @_builtins.property
    def meters(self) -> _containers.RepeatedCompositeFieldContainer[Global___Meter]: ...
    @_builtins.property
    def direct_meters(self) -> _containers.RepeatedCompositeFieldContainer[Global___DirectMeter]: ...
    @_builtins.property
    def controller_packet_metadata(self) -> _containers.RepeatedCompositeFieldContainer[Global___ControllerPacketMetadata]: ...
    @_builtins.property
    def value_sets(self) -> _containers.RepeatedCompositeFieldContainer[Global___ValueSet]: ...
    @_builtins.property
    def registers(self) -> _containers.RepeatedCompositeFieldContainer[Global___Register]: ...
    @_builtins.property
    def digests(self) -> _containers.RepeatedCompositeFieldContainer[Global___Digest]: ...
    @_builtins.property
    def externs(self) -> _containers.RepeatedCompositeFieldContainer[Global___Extern]: ...
    @_builtins.property
    def type_info(self) -> _p4types_pb2.P4TypeInfo: ...
    def __init__(
        self,
        *,
        pkg_info: Global___PkgInfo | None = ...,
        tables: _abc.Iterable[Global___Table] | None = ...,
        actions: _abc.Iterable[Global___Action] | None = ...,
        action_profiles: _abc.Iterable[Global___ActionProfile] | None = ...,
        counters: _abc.Iterable[Global___Counter] | None = ...,
        direct_counters: _abc.Iterable[Global___DirectCounter] | None = ...,
        meters: _abc.Iterable[Global___Meter] | None = ...,
        direct_meters: _abc.Iterable[Global___DirectMeter] | None = ...,
        controller_packet_metadata: _abc.Iterable[Global___ControllerPacketMetadata] | None = ...,
        value_sets: _abc.Iterable[Global___ValueSet] | None = ...,
        registers: _abc.Iterable[Global___Register] | None = ...,
        digests: _abc.Iterable[Global___Digest] | None = ...,
        externs: _abc.Iterable[Global___Extern] | None = ...,
        type_info: _p4types_pb2.P4TypeInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pkg_info", b"pkg_info", "type_info", b"type_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action_profiles", b"action_profiles", "actions", b"actions", "controller_packet_metadata", b"controller_packet_metadata", "counters", b"counters", "digests", b"digests", "direct_counters", b"direct_counters", "direct_meters", b"direct_meters", "externs", b"externs", "meters", b"meters", "pkg_info", b"pkg_info", "registers", b"registers", "tables", b"tables", "type_info", b"type_info", "value_sets", b"value_sets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___P4Info: _TypeAlias = P4Info  # noqa: Y015

@_typing.final
class Documentation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BRIEF_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    brief: _builtins.str
    """A brief description of something, e.g. one sentence"""
    description: _builtins.str
    """A more verbose description of something. Multiline is accepted. Markup
    format (if any) is TBD.
    """
    def __init__(
        self,
        *,
        brief: _builtins.str = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["brief", b"brief", "description", b"description"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Documentation: _TypeAlias = Documentation  # noqa: Y015

@_typing.final
class PlatformProperties(_message.Message):
    """Used to describe the required properties of the underlying platform.
    Added in v1.4.0
    """

    DESCRIPTOR: _descriptor.Descriptor

    MULTICAST_GROUP_TABLE_SIZE_FIELD_NUMBER: _builtins.int
    MULTICAST_GROUP_TABLE_TOTAL_REPLICAS_FIELD_NUMBER: _builtins.int
    MULTICAST_GROUP_TABLE_MAX_REPLICAS_PER_ENTRY_FIELD_NUMBER: _builtins.int
    multicast_group_table_size: _builtins.int
    """The minimum number of multicast entries (i.e. multicast groups) that the
    platform is required to support. If 0, there are no requirements.
    """
    multicast_group_table_total_replicas: _builtins.int
    """The minimum number of replicas that the platform is required to support
    across all  groups. If 0, there are no requirements.
    """
    multicast_group_table_max_replicas_per_entry: _builtins.int
    """The number of replicas that the platform is required to support per
    group/entry. If 0, `multicast_group_table_total_replicas` should be used.
    Must be no larger than `multicast_group_table_total_replicas`.
    """
    def __init__(
        self,
        *,
        multicast_group_table_size: _builtins.int = ...,
        multicast_group_table_total_replicas: _builtins.int = ...,
        multicast_group_table_max_replicas_per_entry: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["multicast_group_table_max_replicas_per_entry", b"multicast_group_table_max_replicas_per_entry", "multicast_group_table_size", b"multicast_group_table_size", "multicast_group_table_total_replicas", b"multicast_group_table_total_replicas"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PlatformProperties: _TypeAlias = PlatformProperties  # noqa: Y015

@_typing.final
class PkgInfo(_message.Message):
    """Top-level package documentation describing the forwarding pipeline config
    Can be used to manage multiple P4 packages.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    DOC_FIELD_NUMBER: _builtins.int
    ANNOTATIONS_FIELD_NUMBER: _builtins.int
    ANNOTATION_LOCATIONS_FIELD_NUMBER: _builtins.int
    ARCH_FIELD_NUMBER: _builtins.int
    ORGANIZATION_FIELD_NUMBER: _builtins.int
    CONTACT_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    STRUCTURED_ANNOTATIONS_FIELD_NUMBER: _builtins.int
    PLATFORM_PROPERTIES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """a definitive name for this configuration, e.g. switch.p4_v1.0"""
    version: _builtins.str
    """configuration version, free-format string"""
    arch: _builtins.str
    """the target architecture, e.g. "psa" """
    organization: _builtins.str
    """organization which produced the configuration, e.g. "p4.org" """
    contact: _builtins.str
    """contact info for support,e.g. "tech-support@acme.org" """
    url: _builtins.str
    """url for more information, e.g.
    "http://support.p4.org/ref/p4/switch.p4_v1.0"
    """
    @_builtins.property
    def doc(self) -> Global___Documentation:
        """brief and detailed descriptions"""

    @_builtins.property
    def annotations(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Miscellaneous metadata, free-form; a way to extend PkgInfo"""

    @_builtins.property
    def annotation_locations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.SourceLocation]:
        """Optional. If present, the location of `annotations[i]` is given by
        `annotation_locations[i]`.
        """

    @_builtins.property
    def structured_annotations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.StructuredAnnotation]:
        """Miscellaneous metadata, structured; a way to extend PkgInfo"""

    @_builtins.property
    def platform_properties(self) -> Global___PlatformProperties:
        """If set, specifies the properties that the underlying platform should have.
        If the platform does not conform to these properties, the server should
        reject the P4Info when used with a SetForwardingPipelineConfigRequest.
        Added in 1.4.0
        """

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        version: _builtins.str = ...,
        doc: Global___Documentation | None = ...,
        annotations: _abc.Iterable[_builtins.str] | None = ...,
        annotation_locations: _abc.Iterable[_p4types_pb2.SourceLocation] | None = ...,
        arch: _builtins.str = ...,
        organization: _builtins.str = ...,
        contact: _builtins.str = ...,
        url: _builtins.str = ...,
        structured_annotations: _abc.Iterable[_p4types_pb2.StructuredAnnotation] | None = ...,
        platform_properties: Global___PlatformProperties | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["doc", b"doc", "platform_properties", b"platform_properties"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["annotation_locations", b"annotation_locations", "annotations", b"annotations", "arch", b"arch", "contact", b"contact", "doc", b"doc", "name", b"name", "organization", b"organization", "platform_properties", b"platform_properties", "structured_annotations", b"structured_annotations", "url", b"url", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PkgInfo: _TypeAlias = PkgInfo  # noqa: Y015

@_typing.final
class P4Ids(_message.Message):
    """wrapping the enum in a message to avoid name collisions in C++, where "enum
    values are siblings of their type, not children of it"
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Prefix:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PrefixEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[P4Ids._Prefix.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNSPECIFIED: P4Ids._Prefix.ValueType  # 0
        ACTION: P4Ids._Prefix.ValueType  # 1
        """P4 language built-ins"""
        TABLE: P4Ids._Prefix.ValueType  # 2
        VALUE_SET: P4Ids._Prefix.ValueType  # 3
        CONTROLLER_HEADER: P4Ids._Prefix.ValueType  # 4
        PSA_EXTERNS_START: P4Ids._Prefix.ValueType  # 16
        """PSA externs"""
        ACTION_PROFILE: P4Ids._Prefix.ValueType  # 17
        COUNTER: P4Ids._Prefix.ValueType  # 18
        DIRECT_COUNTER: P4Ids._Prefix.ValueType  # 19
        METER: P4Ids._Prefix.ValueType  # 20
        DIRECT_METER: P4Ids._Prefix.ValueType  # 21
        REGISTER: P4Ids._Prefix.ValueType  # 22
        DIGEST: P4Ids._Prefix.ValueType  # 23
        OTHER_EXTERNS_START: P4Ids._Prefix.ValueType  # 128
        """externs for other architectures (vendor extensions)"""
        MAX: P4Ids._Prefix.ValueType  # 255
        """max value for an unsigned 8-bit byte
        requires protoc >= 3.5.0
        reserved 0x100 to max;
        """

    class Prefix(_Prefix, metaclass=_PrefixEnumTypeWrapper):
        """ids are allocated in such a way that it is possible based on an id to
        deduce the resource type (e.g. table, action, counter, ...). The
        most-significant byte of the 32-bit id encodes the resource type. The
        purpose of this enum is to define which value is used as the
        most-significant byte for each resource type. The P4 compiler must use
        these values when allocating ids for P4 objects. Other users of P4Info can
        refer to this enum to identify a resource type based on its id.
        """

    UNSPECIFIED: P4Ids.Prefix.ValueType  # 0
    ACTION: P4Ids.Prefix.ValueType  # 1
    """P4 language built-ins"""
    TABLE: P4Ids.Prefix.ValueType  # 2
    VALUE_SET: P4Ids.Prefix.ValueType  # 3
    CONTROLLER_HEADER: P4Ids.Prefix.ValueType  # 4
    PSA_EXTERNS_START: P4Ids.Prefix.ValueType  # 16
    """PSA externs"""
    ACTION_PROFILE: P4Ids.Prefix.ValueType  # 17
    COUNTER: P4Ids.Prefix.ValueType  # 18
    DIRECT_COUNTER: P4Ids.Prefix.ValueType  # 19
    METER: P4Ids.Prefix.ValueType  # 20
    DIRECT_METER: P4Ids.Prefix.ValueType  # 21
    REGISTER: P4Ids.Prefix.ValueType  # 22
    DIGEST: P4Ids.Prefix.ValueType  # 23
    OTHER_EXTERNS_START: P4Ids.Prefix.ValueType  # 128
    """externs for other architectures (vendor extensions)"""
    MAX: P4Ids.Prefix.ValueType  # 255
    """max value for an unsigned 8-bit byte
    requires protoc >= 3.5.0
    reserved 0x100 to max;
    """

    def __init__(
        self,
    ) -> None: ...

Global___P4Ids: _TypeAlias = P4Ids  # noqa: Y015

@_typing.final
class Preamble(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    ALIAS_FIELD_NUMBER: _builtins.int
    ANNOTATIONS_FIELD_NUMBER: _builtins.int
    ANNOTATION_LOCATIONS_FIELD_NUMBER: _builtins.int
    DOC_FIELD_NUMBER: _builtins.int
    STRUCTURED_ANNOTATIONS_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    """ids share the same number-space; e.g. table ids cannot overlap with counter
    ids. Even though this is irrelevant to this proto definition, the ids are
    allocated in such a way that it is possible based on an id to deduce the
    resource type (e.g. table, action, counter, ...). This means that code
    using these ids can detect if the wrong resource type is used
    somewhere. This also means that ids of different types can be mixed
    (e.g. direct resource list for a table) without ambiguity. Note that id 0
    is reserved and means "invalid id".
    """
    name: _builtins.str
    """fully qualified name of the P4 object, e.g. c1.c2.ipv4_lpm"""
    alias: _builtins.str
    """an alias (alternative name) for the P4 object, probably shorter than its
    fully qualified name. The only constraint is for it to be unique with
    respect to other P4 objects of the same type. By default, the compiler uses
    the shortest suffix of the name that uniquely identifies the object. For
    example if the P4 program contains two tables with names s.c1.t and s.c2.t,
    the default aliases will respectively be c1.t and c2.t. In the future, the
    P4 programmer may also be able to override the default alias for any P4
    object (TBD).
    """
    @_builtins.property
    def annotations(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def annotation_locations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.SourceLocation]:
        """Optional. If present, the location of `annotations[i]` is given by
        `annotation_locations[i]`.
        """

    @_builtins.property
    def doc(self) -> Global___Documentation:
        """Documentation of the entity"""

    @_builtins.property
    def structured_annotations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.StructuredAnnotation]: ...
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        name: _builtins.str = ...,
        alias: _builtins.str = ...,
        annotations: _abc.Iterable[_builtins.str] | None = ...,
        annotation_locations: _abc.Iterable[_p4types_pb2.SourceLocation] | None = ...,
        doc: Global___Documentation | None = ...,
        structured_annotations: _abc.Iterable[_p4types_pb2.StructuredAnnotation] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["doc", b"doc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alias", b"alias", "annotation_locations", b"annotation_locations", "annotations", b"annotations", "doc", b"doc", "id", b"id", "name", b"name", "structured_annotations", b"structured_annotations"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Preamble: _TypeAlias = Preamble  # noqa: Y015

@_typing.final
class Extern(_message.Message):
    """used to group all extern instances of the same type in one message"""

    DESCRIPTOR: _descriptor.Descriptor

    EXTERN_TYPE_ID_FIELD_NUMBER: _builtins.int
    EXTERN_TYPE_NAME_FIELD_NUMBER: _builtins.int
    INSTANCES_FIELD_NUMBER: _builtins.int
    extern_type_id: _builtins.int
    """the extern_type_id is unique for a given architecture and must be in the
    range [0x81, 0xfe].
    """
    extern_type_name: _builtins.str
    @_builtins.property
    def instances(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExternInstance]: ...
    def __init__(
        self,
        *,
        extern_type_id: _builtins.int = ...,
        extern_type_name: _builtins.str = ...,
        instances: _abc.Iterable[Global___ExternInstance] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extern_type_id", b"extern_type_id", "extern_type_name", b"extern_type_name", "instances", b"instances"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Extern: _TypeAlias = Extern  # noqa: Y015

@_typing.final
class ExternInstance(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PREAMBLE_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def preamble(self) -> Global___Preamble: ...
    @_builtins.property
    def info(self) -> _any_pb2.Any:
        """specific to the extern type, declared in a separate vendor-specific proto
        file
        """

    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        info: _any_pb2.Any | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["info", b"info", "preamble", b"preamble"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["info", b"info", "preamble", b"preamble"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExternInstance: _TypeAlias = ExternInstance  # noqa: Y015

@_typing.final
class MatchField(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _MatchType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _MatchTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MatchField._MatchType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNSPECIFIED: MatchField._MatchType.ValueType  # 0
        EXACT: MatchField._MatchType.ValueType  # 2
        LPM: MatchField._MatchType.ValueType  # 3
        TERNARY: MatchField._MatchType.ValueType  # 4
        RANGE: MatchField._MatchType.ValueType  # 5
        OPTIONAL: MatchField._MatchType.ValueType  # 6

    class MatchType(_MatchType, metaclass=_MatchTypeEnumTypeWrapper): ...
    UNSPECIFIED: MatchField.MatchType.ValueType  # 0
    EXACT: MatchField.MatchType.ValueType  # 2
    LPM: MatchField.MatchType.ValueType  # 3
    TERNARY: MatchField.MatchType.ValueType  # 4
    RANGE: MatchField.MatchType.ValueType  # 5
    OPTIONAL: MatchField.MatchType.ValueType  # 6

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    ANNOTATIONS_FIELD_NUMBER: _builtins.int
    ANNOTATION_LOCATIONS_FIELD_NUMBER: _builtins.int
    BITWIDTH_FIELD_NUMBER: _builtins.int
    MATCH_TYPE_FIELD_NUMBER: _builtins.int
    OTHER_MATCH_TYPE_FIELD_NUMBER: _builtins.int
    DOC_FIELD_NUMBER: _builtins.int
    TYPE_NAME_FIELD_NUMBER: _builtins.int
    STRUCTURED_ANNOTATIONS_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    name: _builtins.str
    bitwidth: _builtins.int
    match_type: Global___MatchField.MatchType.ValueType
    other_match_type: _builtins.str
    """used for architecture-specific match types which are not part of the core
    P4 language or of the PSA architecture.
    """
    @_builtins.property
    def annotations(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def annotation_locations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.SourceLocation]:
        """Optional. If present, the location of `annotations[i]` is given by
        `annotation_locations[i]`.
        """

    @_builtins.property
    def doc(self) -> Global___Documentation:
        """Documentation of the match field"""

    @_builtins.property
    def type_name(self) -> _p4types_pb2.P4NamedType:
        """unset if not user-defined type"""

    @_builtins.property
    def structured_annotations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.StructuredAnnotation]: ...
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        name: _builtins.str = ...,
        annotations: _abc.Iterable[_builtins.str] | None = ...,
        annotation_locations: _abc.Iterable[_p4types_pb2.SourceLocation] | None = ...,
        bitwidth: _builtins.int = ...,
        match_type: Global___MatchField.MatchType.ValueType = ...,
        other_match_type: _builtins.str = ...,
        doc: Global___Documentation | None = ...,
        type_name: _p4types_pb2.P4NamedType | None = ...,
        structured_annotations: _abc.Iterable[_p4types_pb2.StructuredAnnotation] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["doc", b"doc", "match", b"match", "match_type", b"match_type", "other_match_type", b"other_match_type", "type_name", b"type_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["annotation_locations", b"annotation_locations", "annotations", b"annotations", "bitwidth", b"bitwidth", "doc", b"doc", "id", b"id", "match", b"match", "match_type", b"match_type", "name", b"name", "other_match_type", b"other_match_type", "structured_annotations", b"structured_annotations", "type_name", b"type_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_match: _TypeAlias = _typing.Literal["match_type", "other_match_type"]  # noqa: Y015
    _WhichOneofArgType_match: _TypeAlias = _typing.Literal["match", b"match"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_match) -> _WhichOneofReturnType_match | None: ...

Global___MatchField: _TypeAlias = MatchField  # noqa: Y015

@_typing.final
class TableActionCall(_message.Message):
    """A TableActionCall references a particular action id and executes the
    action with the supplied list of arguments.
    Arguments are matched to the id of the respective action parameter.
    TableActionCalls may be used as the default action call of a table implementation.
    Added in 1.4.0.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Argument(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PARAM_ID_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        param_id: _builtins.int
        value: _builtins.bytes
        def __init__(
            self,
            *,
            param_id: _builtins.int = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["param_id", b"param_id", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ACTION_ID_FIELD_NUMBER: _builtins.int
    ARGUMENTS_FIELD_NUMBER: _builtins.int
    action_id: _builtins.int
    @_builtins.property
    def arguments(self) -> _containers.RepeatedCompositeFieldContainer[Global___TableActionCall.Argument]: ...
    def __init__(
        self,
        *,
        action_id: _builtins.int = ...,
        arguments: _abc.Iterable[Global___TableActionCall.Argument] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action_id", b"action_id", "arguments", b"arguments"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TableActionCall: _TypeAlias = TableActionCall  # noqa: Y015

@_typing.final
class Table(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _IdleTimeoutBehavior:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _IdleTimeoutBehaviorEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Table._IdleTimeoutBehavior.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NO_TIMEOUT: Table._IdleTimeoutBehavior.ValueType  # 0
        NOTIFY_CONTROL: Table._IdleTimeoutBehavior.ValueType  # 1

    class IdleTimeoutBehavior(_IdleTimeoutBehavior, metaclass=_IdleTimeoutBehaviorEnumTypeWrapper):
        """this enum can be extended in the future with other behaviors, such as
        "HARD_EVICTION"
        """

    NO_TIMEOUT: Table.IdleTimeoutBehavior.ValueType  # 0
    NOTIFY_CONTROL: Table.IdleTimeoutBehavior.ValueType  # 1

    PREAMBLE_FIELD_NUMBER: _builtins.int
    MATCH_FIELDS_FIELD_NUMBER: _builtins.int
    ACTION_REFS_FIELD_NUMBER: _builtins.int
    CONST_DEFAULT_ACTION_ID_FIELD_NUMBER: _builtins.int
    INITIAL_DEFAULT_ACTION_FIELD_NUMBER: _builtins.int
    IMPLEMENTATION_ID_FIELD_NUMBER: _builtins.int
    DIRECT_RESOURCE_IDS_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    IDLE_TIMEOUT_BEHAVIOR_FIELD_NUMBER: _builtins.int
    IS_CONST_TABLE_FIELD_NUMBER: _builtins.int
    HAS_INITIAL_ENTRIES_FIELD_NUMBER: _builtins.int
    OTHER_PROPERTIES_FIELD_NUMBER: _builtins.int
    const_default_action_id: _builtins.int
    """0 (default value) means that the table does not have a const default action"""
    implementation_id: _builtins.int
    """P4 id of the "implementation" for this table (e.g. action profile id); 0
    (default value) means that the table is a regular (direct) match table. As
    of today, only action profiles are supported but other table
    implementations may be added in the future
    """
    size: _builtins.int
    """max number of entries in table"""
    idle_timeout_behavior: Global___Table.IdleTimeoutBehavior.ValueType
    """is idle timeout supported for this table?"""
    is_const_table: _builtins.bool
    """True if and only if the table's entries are immutable,
    i.e. defined using the 'const entries' table property in the P4
    source code, and thus entries cannot be deleted, modified, or
    inserted at run time.
    """
    has_initial_entries: _builtins.bool
    """True if and only if the table has initial entries defined using
    the 'entries' table property in the P4 source code, either with
    or without the 'const' qualifier on 'entries', and there is at
    least one entry in that list.  This field is false if the list of
    entries is empty in the P4 source code.
    Added in 1.4.0.
    """
    @_builtins.property
    def preamble(self) -> Global___Preamble: ...
    @_builtins.property
    def match_fields(self) -> _containers.RepeatedCompositeFieldContainer[Global___MatchField]: ...
    @_builtins.property
    def action_refs(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActionRef]:
        """even when the table is indirect (see implementation_id) below, this field
        includes all possible actions for the table; by using ActionRef instead of
        a repeated field of action ids, each action reference in a P4 table is able
        to have its own annotations
        """

    @_builtins.property
    def initial_default_action(self) -> Global___TableActionCall:
        """The initial default action of the table. This can be overridden at runtime.
        Added in 1.4.0.
        """

    @_builtins.property
    def direct_resource_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """ids of the direct resources (if any) attached to this table; for now this
        includes only direct counters and direct meters, but other resources may be
        added in the future
        """

    @_builtins.property
    def other_properties(self) -> _any_pb2.Any:
        """architecture-specific table properties which are not part of the core P4
        language or of the PSA architecture.
        """

    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        match_fields: _abc.Iterable[Global___MatchField] | None = ...,
        action_refs: _abc.Iterable[Global___ActionRef] | None = ...,
        const_default_action_id: _builtins.int = ...,
        initial_default_action: Global___TableActionCall | None = ...,
        implementation_id: _builtins.int = ...,
        direct_resource_ids: _abc.Iterable[_builtins.int] | None = ...,
        size: _builtins.int = ...,
        idle_timeout_behavior: Global___Table.IdleTimeoutBehavior.ValueType = ...,
        is_const_table: _builtins.bool = ...,
        has_initial_entries: _builtins.bool = ...,
        other_properties: _any_pb2.Any | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["initial_default_action", b"initial_default_action", "other_properties", b"other_properties", "preamble", b"preamble"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action_refs", b"action_refs", "const_default_action_id", b"const_default_action_id", "direct_resource_ids", b"direct_resource_ids", "has_initial_entries", b"has_initial_entries", "idle_timeout_behavior", b"idle_timeout_behavior", "implementation_id", b"implementation_id", "initial_default_action", b"initial_default_action", "is_const_table", b"is_const_table", "match_fields", b"match_fields", "other_properties", b"other_properties", "preamble", b"preamble", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Table: _TypeAlias = Table  # noqa: Y015

@_typing.final
class ActionRef(_message.Message):
    """used to list all possible actions in a Table"""

    DESCRIPTOR: _descriptor.Descriptor

    class _Scope:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ScopeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ActionRef._Scope.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TABLE_AND_DEFAULT: ActionRef._Scope.ValueType  # 0
        TABLE_ONLY: ActionRef._Scope.ValueType  # 1
        DEFAULT_ONLY: ActionRef._Scope.ValueType  # 2

    class Scope(_Scope, metaclass=_ScopeEnumTypeWrapper): ...
    TABLE_AND_DEFAULT: ActionRef.Scope.ValueType  # 0
    TABLE_ONLY: ActionRef.Scope.ValueType  # 1
    DEFAULT_ONLY: ActionRef.Scope.ValueType  # 2

    ID_FIELD_NUMBER: _builtins.int
    SCOPE_FIELD_NUMBER: _builtins.int
    ANNOTATIONS_FIELD_NUMBER: _builtins.int
    ANNOTATION_LOCATIONS_FIELD_NUMBER: _builtins.int
    STRUCTURED_ANNOTATIONS_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    scope: Global___ActionRef.Scope.ValueType
    @_builtins.property
    def annotations(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def annotation_locations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.SourceLocation]:
        """Optional. If present, the location of `annotations[i]` is given by
        `annotation_locations[i]`.
        """

    @_builtins.property
    def structured_annotations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.StructuredAnnotation]: ...
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        scope: Global___ActionRef.Scope.ValueType = ...,
        annotations: _abc.Iterable[_builtins.str] | None = ...,
        annotation_locations: _abc.Iterable[_p4types_pb2.SourceLocation] | None = ...,
        structured_annotations: _abc.Iterable[_p4types_pb2.StructuredAnnotation] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["annotation_locations", b"annotation_locations", "annotations", b"annotations", "id", b"id", "scope", b"scope", "structured_annotations", b"structured_annotations"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionRef: _TypeAlias = ActionRef  # noqa: Y015

@_typing.final
class Action(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Param(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ID_FIELD_NUMBER: _builtins.int
        NAME_FIELD_NUMBER: _builtins.int
        ANNOTATIONS_FIELD_NUMBER: _builtins.int
        ANNOTATION_LOCATIONS_FIELD_NUMBER: _builtins.int
        BITWIDTH_FIELD_NUMBER: _builtins.int
        DOC_FIELD_NUMBER: _builtins.int
        TYPE_NAME_FIELD_NUMBER: _builtins.int
        STRUCTURED_ANNOTATIONS_FIELD_NUMBER: _builtins.int
        id: _builtins.int
        name: _builtins.str
        bitwidth: _builtins.int
        @_builtins.property
        def annotations(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        @_builtins.property
        def annotation_locations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.SourceLocation]:
            """Optional. If present, the location of `annotations[i]` is given by
            `annotation_locations[i]`.
            """

        @_builtins.property
        def doc(self) -> Global___Documentation:
            """Documentation of the Param."""

        @_builtins.property
        def type_name(self) -> _p4types_pb2.P4NamedType:
            """unset if not user-defined type."""

        @_builtins.property
        def structured_annotations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.StructuredAnnotation]: ...
        def __init__(
            self,
            *,
            id: _builtins.int = ...,
            name: _builtins.str = ...,
            annotations: _abc.Iterable[_builtins.str] | None = ...,
            annotation_locations: _abc.Iterable[_p4types_pb2.SourceLocation] | None = ...,
            bitwidth: _builtins.int = ...,
            doc: Global___Documentation | None = ...,
            type_name: _p4types_pb2.P4NamedType | None = ...,
            structured_annotations: _abc.Iterable[_p4types_pb2.StructuredAnnotation] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["doc", b"doc", "type_name", b"type_name"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["annotation_locations", b"annotation_locations", "annotations", b"annotations", "bitwidth", b"bitwidth", "doc", b"doc", "id", b"id", "name", b"name", "structured_annotations", b"structured_annotations", "type_name", b"type_name"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PREAMBLE_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def preamble(self) -> Global___Preamble: ...
    @_builtins.property
    def params(self) -> _containers.RepeatedCompositeFieldContainer[Global___Action.Param]: ...
    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        params: _abc.Iterable[Global___Action.Param] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["preamble", b"preamble"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["params", b"params", "preamble", b"preamble"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Action: _TypeAlias = Action  # noqa: Y015

@_typing.final
class ActionProfile(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SumOfWeights(_message.Message):
        """indicates that `size` and `max_group_size` represent the maximum sum of
        weights that can be present across all selector groups and within a
        single selector group respectively.
        Added in v1.4.0.
        """

        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @_typing.final
    class SumOfMembers(_message.Message):
        """indicates that `size` and `max_group_size` represent the maximum number
        of members that can be present across all selector groups and within a
        single selector group respectively.
        Added in v1.4.0.
        """

        DESCRIPTOR: _descriptor.Descriptor

        MAX_MEMBER_WEIGHT_FIELD_NUMBER: _builtins.int
        max_member_weight: _builtins.int
        """the maximum weight of each individual member in a group."""
        def __init__(
            self,
            *,
            max_member_weight: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["max_member_weight", b"max_member_weight"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PREAMBLE_FIELD_NUMBER: _builtins.int
    TABLE_IDS_FIELD_NUMBER: _builtins.int
    WITH_SELECTOR_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    MAX_GROUP_SIZE_FIELD_NUMBER: _builtins.int
    SUM_OF_WEIGHTS_FIELD_NUMBER: _builtins.int
    SUM_OF_MEMBERS_FIELD_NUMBER: _builtins.int
    WEIGHTS_DISALLOWED_FIELD_NUMBER: _builtins.int
    with_selector: _builtins.bool
    """true iff the action profile used dynamic selection"""
    size: _builtins.int
    """max number of member entries across all groups if the action profile does
    not have a selector. Otherwise, semantics as specified by
    `selector_size_semantics` below.
    """
    max_group_size: _builtins.int
    """0 if the action profile does not have a selector. Otherwise, semantics as
    specified by `selector_size_semantics` below.
    """
    weights_disallowed: _builtins.bool
    """Dictates whether the controller can specify weights for groups programmed
    in this ActionProfile. If `weights_disallowed` is true, then all weights
    must be absent. Unset (false) in action profiles without selectors.
    Added in v1.5.0.
    """
    @_builtins.property
    def preamble(self) -> Global___Preamble: ...
    @_builtins.property
    def table_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """the ids of the tables sharing this action profile"""

    @_builtins.property
    def sum_of_weights(self) -> Global___ActionProfile.SumOfWeights:
        """group size is the sum of the group's weights.
        Added in v1.4.0.
        """

    @_builtins.property
    def sum_of_members(self) -> Global___ActionProfile.SumOfMembers:
        """group size is the sum of the group's members.
        Added in v1.4.0.
        """

    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        table_ids: _abc.Iterable[_builtins.int] | None = ...,
        with_selector: _builtins.bool = ...,
        size: _builtins.int = ...,
        max_group_size: _builtins.int = ...,
        sum_of_weights: Global___ActionProfile.SumOfWeights | None = ...,
        sum_of_members: Global___ActionProfile.SumOfMembers | None = ...,
        weights_disallowed: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["preamble", b"preamble", "selector_size_semantics", b"selector_size_semantics", "sum_of_members", b"sum_of_members", "sum_of_weights", b"sum_of_weights"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_group_size", b"max_group_size", "preamble", b"preamble", "selector_size_semantics", b"selector_size_semantics", "size", b"size", "sum_of_members", b"sum_of_members", "sum_of_weights", b"sum_of_weights", "table_ids", b"table_ids", "weights_disallowed", b"weights_disallowed", "with_selector", b"with_selector"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_selector_size_semantics: _TypeAlias = _typing.Literal["sum_of_weights", "sum_of_members"]  # noqa: Y015
    _WhichOneofArgType_selector_size_semantics: _TypeAlias = _typing.Literal["selector_size_semantics", b"selector_size_semantics"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_selector_size_semantics) -> _WhichOneofReturnType_selector_size_semantics | None: ...

Global___ActionProfile: _TypeAlias = ActionProfile  # noqa: Y015

@_typing.final
class CounterSpec(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Unit:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _UnitEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[CounterSpec._Unit.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNSPECIFIED: CounterSpec._Unit.ValueType  # 0
        BYTES: CounterSpec._Unit.ValueType  # 1
        PACKETS: CounterSpec._Unit.ValueType  # 2
        BOTH: CounterSpec._Unit.ValueType  # 3

    class Unit(_Unit, metaclass=_UnitEnumTypeWrapper):
        """Corresponds to 'type' constructor parameter for Counter / DirectCounter in
        PSA
        """

    UNSPECIFIED: CounterSpec.Unit.ValueType  # 0
    BYTES: CounterSpec.Unit.ValueType  # 1
    PACKETS: CounterSpec.Unit.ValueType  # 2
    BOTH: CounterSpec.Unit.ValueType  # 3

    UNIT_FIELD_NUMBER: _builtins.int
    unit: Global___CounterSpec.Unit.ValueType
    def __init__(
        self,
        *,
        unit: Global___CounterSpec.Unit.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["unit", b"unit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CounterSpec: _TypeAlias = CounterSpec  # noqa: Y015

@_typing.final
class Counter(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PREAMBLE_FIELD_NUMBER: _builtins.int
    SPEC_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    INDEX_TYPE_NAME_FIELD_NUMBER: _builtins.int
    size: _builtins.int
    """number of entries in the counter array"""
    @_builtins.property
    def preamble(self) -> Global___Preamble: ...
    @_builtins.property
    def spec(self) -> Global___CounterSpec: ...
    @_builtins.property
    def index_type_name(self) -> _p4types_pb2.P4NamedType:
        """unset if index is not user-defined type"""

    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        spec: Global___CounterSpec | None = ...,
        size: _builtins.int = ...,
        index_type_name: _p4types_pb2.P4NamedType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["index_type_name", b"index_type_name", "preamble", b"preamble", "spec", b"spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["index_type_name", b"index_type_name", "preamble", b"preamble", "size", b"size", "spec", b"spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Counter: _TypeAlias = Counter  # noqa: Y015

@_typing.final
class DirectCounter(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PREAMBLE_FIELD_NUMBER: _builtins.int
    SPEC_FIELD_NUMBER: _builtins.int
    DIRECT_TABLE_ID_FIELD_NUMBER: _builtins.int
    direct_table_id: _builtins.int
    """the id of the table to which the counter is attached"""
    @_builtins.property
    def preamble(self) -> Global___Preamble: ...
    @_builtins.property
    def spec(self) -> Global___CounterSpec: ...
    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        spec: Global___CounterSpec | None = ...,
        direct_table_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["preamble", b"preamble", "spec", b"spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["direct_table_id", b"direct_table_id", "preamble", b"preamble", "spec", b"spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DirectCounter: _TypeAlias = DirectCounter  # noqa: Y015

@_typing.final
class MeterSpec(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Unit:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _UnitEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MeterSpec._Unit.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNSPECIFIED: MeterSpec._Unit.ValueType  # 0
        BYTES: MeterSpec._Unit.ValueType  # 1
        PACKETS: MeterSpec._Unit.ValueType  # 2

    class Unit(_Unit, metaclass=_UnitEnumTypeWrapper):
        """Corresponds to 'type' constructor parameter for Meter / DirectMeter in PSA"""

    UNSPECIFIED: MeterSpec.Unit.ValueType  # 0
    BYTES: MeterSpec.Unit.ValueType  # 1
    PACKETS: MeterSpec.Unit.ValueType  # 2

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MeterSpec._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TWO_RATE_THREE_COLOR: MeterSpec._Type.ValueType  # 0
        """As described in RFC 2698, allows meters to use two rates to split packets
        into three potential colors.
        MeterConfigs on table entries using this meter type MUST have `eburst ==
        0` (i.e. unset).
        """
        SINGLE_RATE_THREE_COLOR: MeterSpec._Type.ValueType  # 1
        """As described in RFC 2697, allows meters to use one rate with an Excess
        Burst Size (EBS) to split packets into three potential colors.
        MeterConfigs on table entries using this meter type MUST have
        `cir == pir && cburst == pburst`.
        """
        SINGLE_RATE_TWO_COLOR: MeterSpec._Type.ValueType  # 2
        """A simplified version of RFC 2697, restricting meters to using a single
        rate to split packets into only RED or GREEN, by not providing an Excess
        Burst Size (EBS).
        MeterConfigs on table entries using this meter type MUST have
        `cir == pir && cburst == pburst && eburst == 0` (i.e. unset).
        """

    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        """Used to restrict the MeterConfigs that can be used to instantiate the
        meter.
        Added in 1.4.0.
        """

    TWO_RATE_THREE_COLOR: MeterSpec.Type.ValueType  # 0
    """As described in RFC 2698, allows meters to use two rates to split packets
    into three potential colors.
    MeterConfigs on table entries using this meter type MUST have `eburst ==
    0` (i.e. unset).
    """
    SINGLE_RATE_THREE_COLOR: MeterSpec.Type.ValueType  # 1
    """As described in RFC 2697, allows meters to use one rate with an Excess
    Burst Size (EBS) to split packets into three potential colors.
    MeterConfigs on table entries using this meter type MUST have
    `cir == pir && cburst == pburst`.
    """
    SINGLE_RATE_TWO_COLOR: MeterSpec.Type.ValueType  # 2
    """A simplified version of RFC 2697, restricting meters to using a single
    rate to split packets into only RED or GREEN, by not providing an Excess
    Burst Size (EBS).
    MeterConfigs on table entries using this meter type MUST have
    `cir == pir && cburst == pburst && eburst == 0` (i.e. unset).
    """

    UNIT_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    unit: Global___MeterSpec.Unit.ValueType
    type: Global___MeterSpec.Type.ValueType
    """Added in 1.4.0."""
    def __init__(
        self,
        *,
        unit: Global___MeterSpec.Unit.ValueType = ...,
        type: Global___MeterSpec.Type.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["type", b"type", "unit", b"unit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MeterSpec: _TypeAlias = MeterSpec  # noqa: Y015

@_typing.final
class Meter(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PREAMBLE_FIELD_NUMBER: _builtins.int
    SPEC_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    INDEX_TYPE_NAME_FIELD_NUMBER: _builtins.int
    size: _builtins.int
    """number of entries in the meter array"""
    @_builtins.property
    def preamble(self) -> Global___Preamble: ...
    @_builtins.property
    def spec(self) -> Global___MeterSpec: ...
    @_builtins.property
    def index_type_name(self) -> _p4types_pb2.P4NamedType:
        """unset if index is not user-defined type"""

    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        spec: Global___MeterSpec | None = ...,
        size: _builtins.int = ...,
        index_type_name: _p4types_pb2.P4NamedType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["index_type_name", b"index_type_name", "preamble", b"preamble", "spec", b"spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["index_type_name", b"index_type_name", "preamble", b"preamble", "size", b"size", "spec", b"spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Meter: _TypeAlias = Meter  # noqa: Y015

@_typing.final
class DirectMeter(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PREAMBLE_FIELD_NUMBER: _builtins.int
    SPEC_FIELD_NUMBER: _builtins.int
    DIRECT_TABLE_ID_FIELD_NUMBER: _builtins.int
    direct_table_id: _builtins.int
    """the id of the table to which the meter is attached"""
    @_builtins.property
    def preamble(self) -> Global___Preamble: ...
    @_builtins.property
    def spec(self) -> Global___MeterSpec: ...
    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        spec: Global___MeterSpec | None = ...,
        direct_table_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["preamble", b"preamble", "spec", b"spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["direct_table_id", b"direct_table_id", "preamble", b"preamble", "spec", b"spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DirectMeter: _TypeAlias = DirectMeter  # noqa: Y015

@_typing.final
class ControllerPacketMetadata(_message.Message):
    """Any metadata associated with controller Packet-IO (Packet-In or Packet-Out)
    is modeled as P4 headers carrying special annotations
    @controller_header("packet_out") and @controller_header("packet_in")
    respectively. There can be at most one header each with these annotations.
    This message captures the info contained within these special headers,
    and used in p4runtime.proto to supply the metadata.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Metadata(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ID_FIELD_NUMBER: _builtins.int
        NAME_FIELD_NUMBER: _builtins.int
        ANNOTATIONS_FIELD_NUMBER: _builtins.int
        ANNOTATION_LOCATIONS_FIELD_NUMBER: _builtins.int
        BITWIDTH_FIELD_NUMBER: _builtins.int
        TYPE_NAME_FIELD_NUMBER: _builtins.int
        STRUCTURED_ANNOTATIONS_FIELD_NUMBER: _builtins.int
        id: _builtins.int
        name: _builtins.str
        """This is the name of the header field (not fully-qualified), similar
        to e.g. Action.Param.name.
        """
        bitwidth: _builtins.int
        @_builtins.property
        def annotations(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        @_builtins.property
        def annotation_locations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.SourceLocation]:
            """Optional. If present, the location of `annotations[i]` is given by
            `annotation_locations[i]`.
            """

        @_builtins.property
        def type_name(self) -> _p4types_pb2.P4NamedType:
            """unset if not user-defined type"""

        @_builtins.property
        def structured_annotations(self) -> _containers.RepeatedCompositeFieldContainer[_p4types_pb2.StructuredAnnotation]: ...
        def __init__(
            self,
            *,
            id: _builtins.int = ...,
            name: _builtins.str = ...,
            annotations: _abc.Iterable[_builtins.str] | None = ...,
            annotation_locations: _abc.Iterable[_p4types_pb2.SourceLocation] | None = ...,
            bitwidth: _builtins.int = ...,
            type_name: _p4types_pb2.P4NamedType | None = ...,
            structured_annotations: _abc.Iterable[_p4types_pb2.StructuredAnnotation] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["type_name", b"type_name"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["annotation_locations", b"annotation_locations", "annotations", b"annotations", "bitwidth", b"bitwidth", "id", b"id", "name", b"name", "structured_annotations", b"structured_annotations", "type_name", b"type_name"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PREAMBLE_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def preamble(self) -> Global___Preamble:
        """preamble.name and preamble.id will specify header type ("packet_out" or
        "packet_in" for now).
        """

    @_builtins.property
    def metadata(self) -> _containers.RepeatedCompositeFieldContainer[Global___ControllerPacketMetadata.Metadata]:
        """Ordered based on header layout.
        This is a constraint on the generator of this P4Info.
        """

    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        metadata: _abc.Iterable[Global___ControllerPacketMetadata.Metadata] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["preamble", b"preamble"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata", "preamble", b"preamble"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ControllerPacketMetadata: _TypeAlias = ControllerPacketMetadata  # noqa: Y015

@_typing.final
class ValueSet(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PREAMBLE_FIELD_NUMBER: _builtins.int
    MATCH_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    size: _builtins.int
    """number of entries in the value_set, as per the P4 constructor call."""
    @_builtins.property
    def preamble(self) -> Global___Preamble: ...
    @_builtins.property
    def match(self) -> _containers.RepeatedCompositeFieldContainer[Global___MatchField]: ...
    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        match: _abc.Iterable[Global___MatchField] | None = ...,
        size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["preamble", b"preamble"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["match", b"match", "preamble", b"preamble", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ValueSet: _TypeAlias = ValueSet  # noqa: Y015

@_typing.final
class Register(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PREAMBLE_FIELD_NUMBER: _builtins.int
    TYPE_SPEC_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    INDEX_TYPE_NAME_FIELD_NUMBER: _builtins.int
    size: _builtins.int
    @_builtins.property
    def preamble(self) -> Global___Preamble: ...
    @_builtins.property
    def type_spec(self) -> _p4types_pb2.P4DataTypeSpec: ...
    @_builtins.property
    def index_type_name(self) -> _p4types_pb2.P4NamedType:
        """unset if index is not user-defined type"""

    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        type_spec: _p4types_pb2.P4DataTypeSpec | None = ...,
        size: _builtins.int = ...,
        index_type_name: _p4types_pb2.P4NamedType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["index_type_name", b"index_type_name", "preamble", b"preamble", "type_spec", b"type_spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["index_type_name", b"index_type_name", "preamble", b"preamble", "size", b"size", "type_spec", b"type_spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Register: _TypeAlias = Register  # noqa: Y015

@_typing.final
class Digest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PREAMBLE_FIELD_NUMBER: _builtins.int
    TYPE_SPEC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def preamble(self) -> Global___Preamble: ...
    @_builtins.property
    def type_spec(self) -> _p4types_pb2.P4DataTypeSpec: ...
    def __init__(
        self,
        *,
        preamble: Global___Preamble | None = ...,
        type_spec: _p4types_pb2.P4DataTypeSpec | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["preamble", b"preamble", "type_spec", b"type_spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["preamble", b"preamble", "type_spec", b"type_spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Digest: _TypeAlias = Digest  # noqa: Y015
