# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12-dev" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true
    - name: Install dependencies
      run: |
        pip install -r ./ci/requirements-dev.txt
    - name: Lint Check
      run: |
        ruff check --exit-zero .
        pylint --fail-under 9.0 finsy
        pyright || echo "Errors ignored for now."
    - name: Run Tests
      run: |
        pytest
    - name: Run Code Coverage
      run: |
        FINSY_TEST_NO_BENCHMARK=1 pytest --cov finsy
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
    - name: Format Check
      run: |
        black --check .
        isort --check .
    - name: Type Check
      run: |
        PYTHONPATH=. pyright --ignoreexternal --verifytypes finsy || echo "Not yet 100%."
