# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]

    env:
      # Skip the test gNMIServer on Python 3.11 (due to seg fault issues).
      FINSY_TEST_GNMI_TARGET: "${{ matrix.python-version == '3.11' && 'skip' || '' }}"
      # Skip the test P4RuntimeServer on Python 3.11 (due to seg fault issues).
      FINSY_TEST_P4RUNTIME_TARGET: "${{ matrix.python-version == '3.11' && 'skip' || '' }}"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./ci/requirements-dev.txt
        pip install flake8
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --statistics
        # Run pylint...
        pylint --fail-under 9.0 finsy
    - name: Run Tests
      run: |
        pytest
    - name: Run Code Coverage
      run: |
        FINSY_TEST_NO_BENCHMARK=1 pytest --cov finsy
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
  