name: demonet

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image
      run: |
        tag="$(date '+%y.%m')"
        docker build --tag ghcr.io/byllyfish/demonet:$tag ci/demonet/. 
        docker push ghcr.io/byllyfish/demonet:$tag
