name: publish

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:

  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Poetry
        run: |
          pipx install poetry==1.6.1
          poetry --version
      - name: Build package
        run: |
          poetry build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e # release/v1
        with:
          user: __token__
          password: ${{ secrets.FINSY_PYPI_API_TOKEN }}
          verbose: true
          print-hash: true
