name: publish

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:

  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up python-3.10
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade setuptools wheel
          python3 -m pip install poetry
      - name: Build package
        run: |
          python3 -m poetry build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e # release/v1
        with:
          user: __token__
          password: ${{ secrets.FINSY_PYPI_API_TOKEN }}
          verbose: true
